/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUser_verificationRouteImport } from './routes/user/user_verification'
import { Route as UserUser_reset_passwordRouteImport } from './routes/user/user_reset_password'
import { Route as UserUser_forget_verifyRouteImport } from './routes/user/user_forget_verify'
import { Route as UserUser_forget_passwordRouteImport } from './routes/user/user_forget_password'
import { Route as UserUserSignupRouteImport } from './routes/user/user-signup'
import { Route as UserUserLoginRouteImport } from './routes/user/user-login'
import { Route as UserRentRouteImport } from './routes/user/rent'
import { Route as UserBuyRentRouteImport } from './routes/user/buy-rent'
import { Route as UserBuyRouteImport } from './routes/user/buy'
import { Route as UserAuthRouteImport } from './routes/user/auth'
import { Route as RegisterRegister_verificationRouteImport } from './routes/register/register_verification'
import { Route as RegisterRegister_signupRouteImport } from './routes/register/register_signup'
import { Route as RegisterRegister_reset_passwordRouteImport } from './routes/register/register_reset_password'
import { Route as RegisterRegister_loginRouteImport } from './routes/register/register_login'
import { Route as RegisterRegister_house_entryRouteImport } from './routes/register/register_house_entry'
import { Route as RegisterRegister_homeRouteImport } from './routes/register/register_home'
import { Route as RegisterRegister_forget_verifyRouteImport } from './routes/register/register_forget_verify'
import { Route as RegisterRegister_forget_passwordRouteImport } from './routes/register/register_forget_password'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUser_verificationRoute = UserUser_verificationRouteImport.update({
  id: '/user/user_verification',
  path: '/user/user_verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUser_reset_passwordRoute = UserUser_reset_passwordRouteImport.update({
  id: '/user/user_reset_password',
  path: '/user/user_reset_password',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUser_forget_verifyRoute = UserUser_forget_verifyRouteImport.update({
  id: '/user/user_forget_verify',
  path: '/user/user_forget_verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUser_forget_passwordRoute =
  UserUser_forget_passwordRouteImport.update({
    id: '/user/user_forget_password',
    path: '/user/user_forget_password',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserUserSignupRoute = UserUserSignupRouteImport.update({
  id: '/user/user-signup',
  path: '/user/user-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserLoginRoute = UserUserLoginRouteImport.update({
  id: '/user/user-login',
  path: '/user/user-login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRentRoute = UserRentRouteImport.update({
  id: '/user/rent',
  path: '/user/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBuyRentRoute = UserBuyRentRouteImport.update({
  id: '/user/buy-rent',
  path: '/user/buy-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBuyRoute = UserBuyRouteImport.update({
  id: '/user/buy',
  path: '/user/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAuthRoute = UserAuthRouteImport.update({
  id: '/user/auth',
  path: '/user/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRegister_verificationRoute =
  RegisterRegister_verificationRouteImport.update({
    id: '/register/register_verification',
    path: '/register/register_verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterRegister_signupRoute = RegisterRegister_signupRouteImport.update({
  id: '/register/register_signup',
  path: '/register/register_signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRegister_reset_passwordRoute =
  RegisterRegister_reset_passwordRouteImport.update({
    id: '/register/register_reset_password',
    path: '/register/register_reset_password',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterRegister_loginRoute = RegisterRegister_loginRouteImport.update({
  id: '/register/register_login',
  path: '/register/register_login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRegister_house_entryRoute =
  RegisterRegister_house_entryRouteImport.update({
    id: '/register/register_house_entry',
    path: '/register/register_house_entry',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterRegister_homeRoute = RegisterRegister_homeRouteImport.update({
  id: '/register/register_home',
  path: '/register/register_home',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRegister_forget_verifyRoute =
  RegisterRegister_forget_verifyRouteImport.update({
    id: '/register/register_forget_verify',
    path: '/register/register_forget_verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterRegister_forget_passwordRoute =
  RegisterRegister_forget_passwordRouteImport.update({
    id: '/register/register_forget_password',
    path: '/register/register_forget_password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/register/register_forget_password': typeof RegisterRegister_forget_passwordRoute
  '/register/register_forget_verify': typeof RegisterRegister_forget_verifyRoute
  '/register/register_home': typeof RegisterRegister_homeRoute
  '/register/register_house_entry': typeof RegisterRegister_house_entryRoute
  '/register/register_login': typeof RegisterRegister_loginRoute
  '/register/register_reset_password': typeof RegisterRegister_reset_passwordRoute
  '/register/register_signup': typeof RegisterRegister_signupRoute
  '/register/register_verification': typeof RegisterRegister_verificationRoute
  '/user/auth': typeof UserAuthRoute
  '/user/buy': typeof UserBuyRoute
  '/user/buy-rent': typeof UserBuyRentRoute
  '/user/rent': typeof UserRentRoute
  '/user/user-login': typeof UserUserLoginRoute
  '/user/user-signup': typeof UserUserSignupRoute
  '/user/user_forget_password': typeof UserUser_forget_passwordRoute
  '/user/user_forget_verify': typeof UserUser_forget_verifyRoute
  '/user/user_reset_password': typeof UserUser_reset_passwordRoute
  '/user/user_verification': typeof UserUser_verificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/register/register_forget_password': typeof RegisterRegister_forget_passwordRoute
  '/register/register_forget_verify': typeof RegisterRegister_forget_verifyRoute
  '/register/register_home': typeof RegisterRegister_homeRoute
  '/register/register_house_entry': typeof RegisterRegister_house_entryRoute
  '/register/register_login': typeof RegisterRegister_loginRoute
  '/register/register_reset_password': typeof RegisterRegister_reset_passwordRoute
  '/register/register_signup': typeof RegisterRegister_signupRoute
  '/register/register_verification': typeof RegisterRegister_verificationRoute
  '/user/auth': typeof UserAuthRoute
  '/user/buy': typeof UserBuyRoute
  '/user/buy-rent': typeof UserBuyRentRoute
  '/user/rent': typeof UserRentRoute
  '/user/user-login': typeof UserUserLoginRoute
  '/user/user-signup': typeof UserUserSignupRoute
  '/user/user_forget_password': typeof UserUser_forget_passwordRoute
  '/user/user_forget_verify': typeof UserUser_forget_verifyRoute
  '/user/user_reset_password': typeof UserUser_reset_passwordRoute
  '/user/user_verification': typeof UserUser_verificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/register/register_forget_password': typeof RegisterRegister_forget_passwordRoute
  '/register/register_forget_verify': typeof RegisterRegister_forget_verifyRoute
  '/register/register_home': typeof RegisterRegister_homeRoute
  '/register/register_house_entry': typeof RegisterRegister_house_entryRoute
  '/register/register_login': typeof RegisterRegister_loginRoute
  '/register/register_reset_password': typeof RegisterRegister_reset_passwordRoute
  '/register/register_signup': typeof RegisterRegister_signupRoute
  '/register/register_verification': typeof RegisterRegister_verificationRoute
  '/user/auth': typeof UserAuthRoute
  '/user/buy': typeof UserBuyRoute
  '/user/buy-rent': typeof UserBuyRentRoute
  '/user/rent': typeof UserRentRoute
  '/user/user-login': typeof UserUserLoginRoute
  '/user/user-signup': typeof UserUserSignupRoute
  '/user/user_forget_password': typeof UserUser_forget_passwordRoute
  '/user/user_forget_verify': typeof UserUser_forget_verifyRoute
  '/user/user_reset_password': typeof UserUser_reset_passwordRoute
  '/user/user_verification': typeof UserUser_verificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/services'
    | '/register/register_forget_password'
    | '/register/register_forget_verify'
    | '/register/register_home'
    | '/register/register_house_entry'
    | '/register/register_login'
    | '/register/register_reset_password'
    | '/register/register_signup'
    | '/register/register_verification'
    | '/user/auth'
    | '/user/buy'
    | '/user/buy-rent'
    | '/user/rent'
    | '/user/user-login'
    | '/user/user-signup'
    | '/user/user_forget_password'
    | '/user/user_forget_verify'
    | '/user/user_reset_password'
    | '/user/user_verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/services'
    | '/register/register_forget_password'
    | '/register/register_forget_verify'
    | '/register/register_home'
    | '/register/register_house_entry'
    | '/register/register_login'
    | '/register/register_reset_password'
    | '/register/register_signup'
    | '/register/register_verification'
    | '/user/auth'
    | '/user/buy'
    | '/user/buy-rent'
    | '/user/rent'
    | '/user/user-login'
    | '/user/user-signup'
    | '/user/user_forget_password'
    | '/user/user_forget_verify'
    | '/user/user_reset_password'
    | '/user/user_verification'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/services'
    | '/register/register_forget_password'
    | '/register/register_forget_verify'
    | '/register/register_home'
    | '/register/register_house_entry'
    | '/register/register_login'
    | '/register/register_reset_password'
    | '/register/register_signup'
    | '/register/register_verification'
    | '/user/auth'
    | '/user/buy'
    | '/user/buy-rent'
    | '/user/rent'
    | '/user/user-login'
    | '/user/user-signup'
    | '/user/user_forget_password'
    | '/user/user_forget_verify'
    | '/user/user_reset_password'
    | '/user/user_verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ServicesRoute: typeof ServicesRoute
  RegisterRegister_forget_passwordRoute: typeof RegisterRegister_forget_passwordRoute
  RegisterRegister_forget_verifyRoute: typeof RegisterRegister_forget_verifyRoute
  RegisterRegister_homeRoute: typeof RegisterRegister_homeRoute
  RegisterRegister_house_entryRoute: typeof RegisterRegister_house_entryRoute
  RegisterRegister_loginRoute: typeof RegisterRegister_loginRoute
  RegisterRegister_reset_passwordRoute: typeof RegisterRegister_reset_passwordRoute
  RegisterRegister_signupRoute: typeof RegisterRegister_signupRoute
  RegisterRegister_verificationRoute: typeof RegisterRegister_verificationRoute
  UserAuthRoute: typeof UserAuthRoute
  UserBuyRoute: typeof UserBuyRoute
  UserBuyRentRoute: typeof UserBuyRentRoute
  UserRentRoute: typeof UserRentRoute
  UserUserLoginRoute: typeof UserUserLoginRoute
  UserUserSignupRoute: typeof UserUserSignupRoute
  UserUser_forget_passwordRoute: typeof UserUser_forget_passwordRoute
  UserUser_forget_verifyRoute: typeof UserUser_forget_verifyRoute
  UserUser_reset_passwordRoute: typeof UserUser_reset_passwordRoute
  UserUser_verificationRoute: typeof UserUser_verificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/user_verification': {
      id: '/user/user_verification'
      path: '/user/user_verification'
      fullPath: '/user/user_verification'
      preLoaderRoute: typeof UserUser_verificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/user_reset_password': {
      id: '/user/user_reset_password'
      path: '/user/user_reset_password'
      fullPath: '/user/user_reset_password'
      preLoaderRoute: typeof UserUser_reset_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/user_forget_verify': {
      id: '/user/user_forget_verify'
      path: '/user/user_forget_verify'
      fullPath: '/user/user_forget_verify'
      preLoaderRoute: typeof UserUser_forget_verifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/user_forget_password': {
      id: '/user/user_forget_password'
      path: '/user/user_forget_password'
      fullPath: '/user/user_forget_password'
      preLoaderRoute: typeof UserUser_forget_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/user-signup': {
      id: '/user/user-signup'
      path: '/user/user-signup'
      fullPath: '/user/user-signup'
      preLoaderRoute: typeof UserUserSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/user-login': {
      id: '/user/user-login'
      path: '/user/user-login'
      fullPath: '/user/user-login'
      preLoaderRoute: typeof UserUserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/rent': {
      id: '/user/rent'
      path: '/user/rent'
      fullPath: '/user/rent'
      preLoaderRoute: typeof UserRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/buy-rent': {
      id: '/user/buy-rent'
      path: '/user/buy-rent'
      fullPath: '/user/buy-rent'
      preLoaderRoute: typeof UserBuyRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/buy': {
      id: '/user/buy'
      path: '/user/buy'
      fullPath: '/user/buy'
      preLoaderRoute: typeof UserBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/auth': {
      id: '/user/auth'
      path: '/user/auth'
      fullPath: '/user/auth'
      preLoaderRoute: typeof UserAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_verification': {
      id: '/register/register_verification'
      path: '/register/register_verification'
      fullPath: '/register/register_verification'
      preLoaderRoute: typeof RegisterRegister_verificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_signup': {
      id: '/register/register_signup'
      path: '/register/register_signup'
      fullPath: '/register/register_signup'
      preLoaderRoute: typeof RegisterRegister_signupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_reset_password': {
      id: '/register/register_reset_password'
      path: '/register/register_reset_password'
      fullPath: '/register/register_reset_password'
      preLoaderRoute: typeof RegisterRegister_reset_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_login': {
      id: '/register/register_login'
      path: '/register/register_login'
      fullPath: '/register/register_login'
      preLoaderRoute: typeof RegisterRegister_loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_house_entry': {
      id: '/register/register_house_entry'
      path: '/register/register_house_entry'
      fullPath: '/register/register_house_entry'
      preLoaderRoute: typeof RegisterRegister_house_entryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_home': {
      id: '/register/register_home'
      path: '/register/register_home'
      fullPath: '/register/register_home'
      preLoaderRoute: typeof RegisterRegister_homeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_forget_verify': {
      id: '/register/register_forget_verify'
      path: '/register/register_forget_verify'
      fullPath: '/register/register_forget_verify'
      preLoaderRoute: typeof RegisterRegister_forget_verifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register_forget_password': {
      id: '/register/register_forget_password'
      path: '/register/register_forget_password'
      fullPath: '/register/register_forget_password'
      preLoaderRoute: typeof RegisterRegister_forget_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ServicesRoute: ServicesRoute,
  RegisterRegister_forget_passwordRoute: RegisterRegister_forget_passwordRoute,
  RegisterRegister_forget_verifyRoute: RegisterRegister_forget_verifyRoute,
  RegisterRegister_homeRoute: RegisterRegister_homeRoute,
  RegisterRegister_house_entryRoute: RegisterRegister_house_entryRoute,
  RegisterRegister_loginRoute: RegisterRegister_loginRoute,
  RegisterRegister_reset_passwordRoute: RegisterRegister_reset_passwordRoute,
  RegisterRegister_signupRoute: RegisterRegister_signupRoute,
  RegisterRegister_verificationRoute: RegisterRegister_verificationRoute,
  UserAuthRoute: UserAuthRoute,
  UserBuyRoute: UserBuyRoute,
  UserBuyRentRoute: UserBuyRentRoute,
  UserRentRoute: UserRentRoute,
  UserUserLoginRoute: UserUserLoginRoute,
  UserUserSignupRoute: UserUserSignupRoute,
  UserUser_forget_passwordRoute: UserUser_forget_passwordRoute,
  UserUser_forget_verifyRoute: UserUser_forget_verifyRoute,
  UserUser_reset_passwordRoute: UserUser_reset_passwordRoute,
  UserUser_verificationRoute: UserUser_verificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
